# E-Commerce Order Analytics System
### Celebal Technologies Data Engineering Internship
**Week 8 Assignment**

**Name:** Samradni Dahiphale  
**Project Duration:** Week 8  
**Technologies Used:** Python, Pandas, SQLite, SQL, Faker, Tabulate, VS Code, Git

## 1. Project Overview

This project builds a complete local analytics workflow for e-commerce order data. It generates source data, cleans quality issues, loads validated records into SQLite, and produces business reports through SQL and a Python CLI.

**Workflow:** Raw CSV generation → cleaning and validation → SQLite loading → SQL analytics → CLI reports → automated testing.

## 2. Problem Statement

- E-commerce data is spread across customer, product, order, and order-item datasets.
- Raw operational data can contain missing values, invalid formats, duplicates, and broken references.
- Business teams need reliable revenue, customer, product, and retention insights.
- The project creates a repeatable pipeline from raw files to validated analytical reports.
- A command-line reporting tool makes the final insights easy to access.

## 3. Tech Stack

In [1]:
import pandas as pd

pd.DataFrame([
    ('Python', 'Pipeline orchestration, validation, CLI, and tests'),
    ('Pandas', 'CSV processing and report DataFrames'),
    ('SQLite', 'Local relational analytics database'),
    ('SQL', 'KPIs, joins, views, CTEs, and window functions'),
    ('Faker', 'Synthetic e-commerce data generation'),
    ('Tabulate', 'Formatted command-line report output'),
    ('VS Code', 'Development environment'),
    ('Git', 'Version control and submission packaging'),
], columns=['Technology', 'Use in Project'])

  Technology                                     Use in Project
0     Python  Pipeline orchestration, validation, CLI, and t...
1     Pandas               CSV processing and report DataFrames
2     SQLite                Local relational analytics database
3        SQL     KPIs, joins, views, CTEs, and window functions
4      Faker               Synthetic e-commerce data generation
5   Tabulate               Formatted command-line report output
6    VS Code                            Development environment
7        Git           Version control and submission packaging

## 4. Project Folder Structure

```text
ecommerce-analytics-system/
├── data/
│   ├── raw/
│   └── cleaned/
├── database/
├── output/
│   ├── reports/
│   ├── sql_reports/
│   ├── advanced_reports/
│   └── tests/
├── scripts/
├── sql/
├── tests/
├── main.py
├── requirements.txt
├── README.md
└── Week8_Ecommerce_Order_Analytics.ipynb
```

## 5. Step 1 – Data Generation

The generator creates realistic e-commerce datasets and deliberately introduces data-quality issues for the cleaning phase.

In [2]:
import sys
from pathlib import Path

project_root = Path.cwd()
if not (project_root / 'scripts').exists():
    project_root = project_root / 'ecommerce-analytics-system'
%cd {project_root}
!{sys.executable} scripts/data_generator.py

d:\Samradni Dahiphale\Projects\Celebal task\Data_Engineering_Internship_Celebal_Technologies\Assignment 8\ecommerce-analytics-system

Traceback (most recent call last):
  File "d:\Samradni Dahiphale\Projects\Celebal task\Data_Engineering_Internship_Celebal_Technologies\Assignment 8\ecommerce-analytics-system\scripts\data_generator.py", line 18, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'

In [3]:
raw_dir = project_root / 'data' / 'raw'
customers = pd.read_csv(raw_dir / 'customers.csv')
products = pd.read_csv(raw_dir / 'products.csv')
orders = pd.read_csv(raw_dir / 'orders.csv')
order_items = pd.read_csv(raw_dir / 'order_items.csv')

display(customers.head())
display(products.head())
display(orders.head())
display(order_items.head())

pd.DataFrame({
    'Dataset': ['Customers', 'Products', 'Orders', 'Order Items'],
    'Rows': [len(customers), len(products), len(orders), len(order_items)],
    'Columns': [customers.shape[1], products.shape[1], orders.shape[1], order_items.shape[1]],
})

,customer_id,customer_name,email,phone,city,state,country,registration_date,customer_type
0,CUST-00001,THEODORE ARYA,invalid-email,NaN,Tiruppur,West Bengal,Senegal,2022-01-24,VIP
1,CUST-00002,Pallavi Som,gautami92@example.com,7.692065e+09,Malda,Nagaland,France,2022-09-16,VIP
2,CUST-00003,Caleb Loyal,ohayre@example.org,9.147788e+11,Gudivada,Nagaland,Sierra Leone,2021-08-26,VIP
3,CUST-00004,Om Samra,oni55@example.net,3.388593e+09,Bhavnagar,Uttar Pradesh,Jordan,2023-12-21,VIP
4,CUST-00005,Harrison Chada,kiaan17@example.net,9.181661e+11,Katihar,Chhattisgarh,Seychelles,2025-12-19,REGULAR

,product_id,product_name,category,subcategory,brand,cost_price,selling_price,stock_quantity
0,PROD-00001,ORBIT OUTDOOR MINIMA,Toys,Outdoor,Orbit,513.11,864.86,-13
1,PROD-00002,Orbit Office Odio,Furniture,Office,Orbit,2937.88,4009.88,51
2,PROD-00003,Bright Men Voluptate,Clothing,Men,Bright,2973.57,5023.52,61
3,PROD-00004,Summit Accessories Vitae,Electronics,Accessories,Summit,1292.40,1880.62,167
4,PROD-00005,Orbit Wellness Fuga,Beauty,Wellness,Orbit,2492.93,3036.67,171

    order_id customer_id  order_date     status region_code payment_method
0  ORD-00001         NaN  2026-09-05  CANCELLED       NORTH            UPI
1  ORD-00002  CUST-00300  2024-01-12   RETURNED        EAST    Credit Card
2  ORD-00003  CUST-00170  2020-01-21     PLACED     CENTRAL     Debit Card
3  ORD-00004  CUST-00002  2023-10-16    SHIPPED     CENTRAL    Net Banking
4  ORD-00005  CUST-00237  2020-07-13  CANCELLED     CENTRAL     Debit Card

   item_id   order_id  product_id  quantity  unit_price  discount_percent
0        1  ORD-99999  PROD-99999         0     1290.44            138.40
1        2  ORD-01334  PROD-00185         7      470.55             42.85
2        3  ORD-00098  PROD-00123         5     1350.76             10.77
3        4  ORD-00559  PROD-00293         1     2084.94              5.53
4        5  ORD-01418  PROD-00211         3     2336.47              8.56

       Dataset  Rows  Columns
0    Customers   500        9
1     Products   300        8
2       Orders  1500        6
3  Order Items  4000        6

## 6. Step 2 – Data Cleaning

The cleaning pipeline standardizes text and dates, fixes numerical values, flags relationship issues, and writes cleaned files and validation summaries.

In [4]:
!{sys.executable} scripts/clean_data.py

Traceback (most recent call last):
  File "d:\Samradni Dahiphale\Projects\Celebal task\Data_Engineering_Internship_Celebal_Technologies\Assignment 8\ecommerce-analytics-system\scripts\clean_data.py", line 9, in <module>
    from scripts.utils import (
    ...<11 lines>...
    )
ModuleNotFoundError: No module named 'scripts'

In [5]:
cleaned_dir = project_root / 'data' / 'cleaned'
customers_clean = pd.read_csv(cleaned_dir / 'customers_clean.csv')
products_clean = pd.read_csv(cleaned_dir / 'products_clean.csv')
orders_clean = pd.read_csv(cleaned_dir / 'orders_clean.csv')
order_items_clean = pd.read_csv(cleaned_dir / 'order_items_clean.csv')

display(customers_clean.head())
display(products_clean.head())
display(orders_clean.head())
display(order_items_clean.head())

,customer_id,customer_name,email,phone,city,state,country,registration_date,customer_type,email_valid
0,CUST-00001,Theodore Arya,invalid-email,Not Available,Tiruppur,West Bengal,Senegal,2022-01-24,VIP,False
1,CUST-00002,Pallavi Som,gautami92@example.com,7692065349.0,Malda,Nagaland,France,2022-09-16,VIP,True
2,CUST-00003,Caleb Loyal,ohayre@example.org,914778779247.0,Gudivada,Nagaland,Sierra Leone,2021-08-26,VIP,True
3,CUST-00004,Om Samra,oni55@example.net,3388593081.0,Bhavnagar,Uttar Pradesh,Jordan,2023-12-21,VIP,True
4,CUST-00005,Harrison Chada,kiaan17@example.net,918166127565.0,Katihar,Chhattisgarh,Seychelles,2025-12-19,REGULAR,True

,product_id,product_name,category,subcategory,brand,cost_price,selling_price,stock_quantity,profit_margin
0,PROD-00001,Orbit Outdoor Minima,Toys,Outdoor,Orbit,513.11,864.86,0.0,68.55
1,PROD-00002,Orbit Office Odio,Furniture,Office,Orbit,2937.88,4009.88,51.0,36.49
2,PROD-00003,Bright Men Voluptate,Clothing,Men,Bright,2973.57,5023.52,61.0,68.94
3,PROD-00004,Summit Accessories Vitae,Electronics,Accessories,Summit,1292.40,1880.62,167.0,45.51
4,PROD-00005,Orbit Wellness Fuga,Beauty,Wellness,Orbit,2492.93,3036.67,171.0,21.81

,order_id,customer_id,order_date,status,region_code,payment_method,customer_exists,valid_customer
0,ORD-00001,NaN,2026-08-10 00:01:11,CANCELLED,NORTH,UPI,False,False
1,ORD-00002,CUST-00300,2024-01-12 00:00:00,RETURNED,EAST,Credit Card,True,True
2,ORD-00003,CUST-00170,2020-01-21 00:00:00,PLACED,CENTRAL,Debit Card,True,True
3,ORD-00004,CUST-00002,2023-10-16 00:00:00,SHIPPED,CENTRAL,Net Banking,True,True
4,ORD-00005,CUST-00237,2020-07-13 00:00:00,CANCELLED,CENTRAL,Debit Card,True,True

,item_id,order_id,product_id,quantity,unit_price,discount_percent,valid_order,valid_product
0,1,ORD-99999,PROD-99999,1,1290.44,100.00,False,False
1,2,ORD-01334,PROD-00185,7,470.55,42.85,True,True
2,3,ORD-00098,PROD-00123,5,1350.76,10.77,True,True
3,4,ORD-00559,PROD-00293,1,2084.94,5.53,True,True
4,5,ORD-01418,PROD-00211,3,2336.47,8.56,True,True

In [6]:
cleaning_summary = pd.read_csv(project_root / 'output' / 'cleaning_summary.csv')
validation_snapshot = pd.DataFrame({
    'Metric': ['Duplicate customers removed', 'Duplicate products removed', 'Missing phone values handled', 'Negative quantities fixed', 'Discount errors fixed'],
    'Value': [
        cleaning_summary['duplicate_customers_removed'].iloc[0],
        cleaning_summary['duplicate_products_removed'].iloc[0],
        cleaning_summary['missing_phone_fixed'].iloc[0],
        cleaning_summary['negative_quantities_fixed'].iloc[0],
        cleaning_summary['discount_errors_fixed'].iloc[0],
    ],
})
display(validation_snapshot)
cleaning_summary

                         Metric  Value
0   Duplicate customers removed      0
1    Duplicate products removed      0
2  Missing phone values handled      4
3     Negative quantities fixed    115
4         Discount errors fixed     27

,customers_loaded,customers_cleaned,duplicate_customers_removed,invalid_emails_corrected,missing_phone_fixed,products_loaded,products_cleaned,duplicate_products_removed,negative_stock_fixed,price_validation_fixes,...,wrong_date_formats_fixed,future_dates_corrected,null_customer_ids_preserved,order_items_loaded,order_items_cleaned,negative_quantities_fixed,discount_errors_fixed,missing_product_ids,missing_order_ids,referential_integrity_issues
0,500,500,0,10,4,300,300,0,4,0,...,0,173,75,4000,4000,115,27,40,32,147

## 7. Step 3 – SQLite Database

The loader recreates the schema, applies constraints and indexes, loads valid records in transactions, and produces a loading report.

In [7]:
!{sys.executable} scripts/load_database.py

import sqlite3

database_path = project_root / 'database' / 'ecommerce.db'
connection = sqlite3.connect(database_path)
tables = pd.read_sql_query("SELECT name AS table_name FROM sqlite_master WHERE type = 'table' ORDER BY name", connection)
display(tables)

record_counts = pd.DataFrame([
    (table, pd.read_sql_query(f'SELECT COUNT(*) AS records FROM {table}', connection).iloc[0, 0])
    for table in tables['table_name']
], columns=['Table', 'Records'])
display(record_counts)

Traceback (most recent call last):
  File "d:\Samradni Dahiphale\Projects\Celebal task\Data_Engineering_Internship_Celebal_Technologies\Assignment 8\ecommerce-analytics-system\scripts\load_database.py", line 12, in <module>
    from scripts.create_database import create_database
ModuleNotFoundError: No module named 'scripts'

    table_name
0    customers
1  order_items
2       orders
3     products

         Table  Records
0    customers      488
1  order_items     3731
2       orders     1383
3     products      300

In [8]:
for table in ['customers', 'products', 'orders', 'order_items']:
    print(f'### {table}')
    display(pd.read_sql_query(f'SELECT * FROM {table} LIMIT 5', connection))

### customers

,customer_id,customer_name,email,phone,city,state,country,registration_date,customer_type
0,CUST-00001,Theodore Arya,invalid-email,Not Available,Tiruppur,West Bengal,Senegal,2022-01-24,VIP
1,CUST-00002,Pallavi Som,gautami92@example.com,7692065349.0,Malda,Nagaland,France,2022-09-16,VIP
2,CUST-00003,Caleb Loyal,ohayre@example.org,914778779247.0,Gudivada,Nagaland,Sierra Leone,2021-08-26,VIP
3,CUST-00004,Om Samra,oni55@example.net,3388593081.0,Bhavnagar,Uttar Pradesh,Jordan,2023-12-21,VIP
4,CUST-00005,Harrison Chada,kiaan17@example.net,918166127565.0,Katihar,Chhattisgarh,Seychelles,2025-12-19,REGULAR

### products

,product_id,product_name,category,subcategory,brand,cost_price,selling_price,stock_quantity,profit_margin
0,PROD-00001,Orbit Outdoor Minima,Toys,Outdoor,Orbit,513.11,864.86,0,68.55
1,PROD-00002,Orbit Office Odio,Furniture,Office,Orbit,2937.88,4009.88,51,36.49
2,PROD-00003,Bright Men Voluptate,Clothing,Men,Bright,2973.57,5023.52,61,68.94
3,PROD-00004,Summit Accessories Vitae,Electronics,Accessories,Summit,1292.40,1880.62,167,45.51
4,PROD-00005,Orbit Wellness Fuga,Beauty,Wellness,Orbit,2492.93,3036.67,171,21.81

### orders

,order_id,customer_id,order_date,status,region_code,payment_method
0,ORD-00002,CUST-00300,2024-01-12 00:00:00,RETURNED,EAST,Credit Card
1,ORD-00003,CUST-00170,2020-01-21 00:00:00,PLACED,CENTRAL,Debit Card
2,ORD-00004,CUST-00002,2023-10-16 00:00:00,SHIPPED,CENTRAL,Net Banking
3,ORD-00005,CUST-00237,2020-07-13 00:00:00,CANCELLED,CENTRAL,Debit Card
4,ORD-00006,CUST-00344,2021-02-17 00:00:00,PLACED,CENTRAL,Net Banking

### order_items

   item_id   order_id  product_id  quantity  unit_price  discount_percent
0        2  ORD-01334  PROD-00185         7      470.55             42.85
1        3  ORD-00098  PROD-00123         5     1350.76             10.77
2        4  ORD-00559  PROD-00293         1     2084.94              5.53
3        5  ORD-01418  PROD-00211         3     2336.47              8.56
4        6  ORD-01043  PROD-00150         3      174.53              5.68

## 8. Step 4 – SQL Analytics

The following queries show category, customer, time, product, and regional performance.

In [9]:
analytics_queries = {
    'Revenue by Category': "SELECT p.category, ROUND(SUM(i.quantity * i.unit_price * (1 - i.discount_percent / 100.0)), 2) AS revenue FROM products p JOIN order_items i ON i.product_id = p.product_id GROUP BY p.category ORDER BY revenue DESC",
    'Top 10 Customers': "SELECT c.customer_name, ROUND(SUM(i.quantity * i.unit_price * (1 - i.discount_percent / 100.0)), 2) AS revenue FROM customers c JOIN orders o ON o.customer_id = c.customer_id JOIN order_items i ON i.order_id = o.order_id GROUP BY c.customer_id, c.customer_name ORDER BY revenue DESC LIMIT 10",
    'Monthly Revenue': "SELECT strftime('%Y-%m', o.order_date) AS sales_month, ROUND(SUM(i.quantity * i.unit_price * (1 - i.discount_percent / 100.0)), 2) AS revenue FROM orders o JOIN order_items i ON i.order_id = o.order_id GROUP BY sales_month ORDER BY sales_month",
    'Top Products': "SELECT p.product_name, SUM(i.quantity) AS units_sold, ROUND(SUM(i.quantity * i.unit_price * (1 - i.discount_percent / 100.0)), 2) AS revenue FROM products p JOIN order_items i ON i.product_id = p.product_id GROUP BY p.product_id, p.product_name ORDER BY revenue DESC LIMIT 10",
    'Revenue by Region': "SELECT o.region_code, ROUND(SUM(i.quantity * i.unit_price * (1 - i.discount_percent / 100.0)), 2) AS revenue FROM orders o JOIN order_items i ON i.order_id = o.order_id GROUP BY o.region_code ORDER BY revenue DESC",
}

for title, query in analytics_queries.items():
    print(f'### {title}')
    display(pd.read_sql_query(query, connection))

### Revenue by Category

      category     revenue
0       Beauty  2123176.46
1  Electronics  1962527.99
2        Books  1861312.34
3    Furniture  1825771.00
4         Toys  1683190.34
5     Clothing  1646325.15
6       Sports  1637180.83
7         Home  1425978.99

### Top 10 Customers

       customer_name    revenue
0     Yatin Dhaliwal  125061.20
1       Liam Chander  116091.71
2       Dalbir Hegde  115815.77
3         Reva Dugar  115179.68
4  Varenya Sabharwal  100300.41
5       Maya Chauhan   99861.51
6     Lakshit Ramesh   90579.34
7         Reva Soman   89413.31
8        Daksh Sarin   82627.95
9         Priya Modi   82533.49

### Monthly Revenue

   sales_month     revenue
0      2020-01   224624.95
1      2020-02   155262.40
2      2020-03   154816.38
3      2020-04   147597.29
4      2020-05   205707.03
..         ...         ...
75     2026-04   166817.19
76     2026-05   112943.64
77     2026-06   184829.18
78     2026-07   102281.75
79     2026-08  1461562.83

[80 rows x 2 columns]

### Top Products

                product_name  units_sold    revenue
0         Urban Office Nulla          94  119834.07
1           Summit Comics Ab          81  102701.74
2     Nexa Office Voluptatem          95   99375.81
3  Urban Accessories Aperiam          69   94145.02
4     Mira Academic Mollitia          76   88071.25
5         Mira Office Facere          77   87413.82
6          River Dining Quas          77   82905.05
7    Urban Educational Harum          62   81701.88
8        Urban  Makeup  Nisi          86   80736.43
9       Mira Seasonal Facere          68   80167.19

### Revenue by Region

  region_code     revenue
0     CENTRAL  2772710.50
1       NORTH  2446702.74
2       SOUTH  2433375.94
3        EAST  2373034.06
4        WEST  2280512.19
5         NCR  1859127.68

## 9. Step 5 – Advanced SQL Analytics

These examples demonstrate ranking, cumulative revenue, CTEs, cohort retention, and customer segmentation.

In [10]:
advanced_queries = {
    'RANK and DENSE_RANK': "WITH customer_value AS (SELECT c.customer_id, c.customer_name, COALESCE(SUM(i.quantity * i.unit_price * (1 - i.discount_percent / 100.0)), 0) AS lifetime_value FROM customers c LEFT JOIN orders o ON o.customer_id = c.customer_id LEFT JOIN order_items i ON i.order_id = o.order_id GROUP BY c.customer_id, c.customer_name) SELECT customer_name, ROUND(lifetime_value, 2) AS lifetime_value, RANK() OVER (ORDER BY lifetime_value DESC) AS value_rank, DENSE_RANK() OVER (ORDER BY lifetime_value DESC) AS dense_rank FROM customer_value LIMIT 10",
    'Running Total': "WITH daily_sales AS (SELECT date(o.order_date) AS sales_date, SUM(i.quantity * i.unit_price * (1 - i.discount_percent / 100.0)) AS daily_revenue FROM orders o JOIN order_items i ON i.order_id = o.order_id GROUP BY date(o.order_date)) SELECT sales_date, ROUND(daily_revenue, 2) AS daily_revenue, ROUND(SUM(daily_revenue) OVER (ORDER BY sales_date), 2) AS running_revenue FROM daily_sales ORDER BY sales_date LIMIT 10",
    'CTE Monthly Revenue': "WITH monthly_sales AS (SELECT strftime('%Y-%m', o.order_date) AS sales_month, SUM(i.quantity * i.unit_price * (1 - i.discount_percent / 100.0)) AS revenue FROM orders o JOIN order_items i ON i.order_id = o.order_id GROUP BY sales_month) SELECT sales_month, ROUND(revenue, 2) AS revenue FROM monthly_sales ORDER BY sales_month",
    'Cohort Retention': "WITH customer_months AS (SELECT customer_id, date(strftime('%Y-%m-01', order_date)) AS purchase_month FROM orders WHERE customer_id IS NOT NULL GROUP BY customer_id, purchase_month), cohorts AS (SELECT customer_id, MIN(purchase_month) AS cohort_month FROM customer_months GROUP BY customer_id), activity AS (SELECT c.cohort_month, ((CAST(strftime('%Y', cm.purchase_month) AS INTEGER) - CAST(strftime('%Y', c.cohort_month) AS INTEGER)) * 12 + CAST(strftime('%m', cm.purchase_month) AS INTEGER) - CAST(strftime('%m', c.cohort_month) AS INTEGER)) AS month_number, cm.customer_id FROM customer_months cm JOIN cohorts c ON c.customer_id = cm.customer_id) SELECT cohort_month, month_number, COUNT(DISTINCT customer_id) AS active_customers FROM activity WHERE month_number BETWEEN 0 AND 3 GROUP BY cohort_month, month_number ORDER BY cohort_month, month_number LIMIT 12",
    'Customer Segmentation': "WITH customer_value AS (SELECT c.customer_id, c.customer_name, COUNT(DISTINCT o.order_id) AS frequency, COALESCE(SUM(i.quantity * i.unit_price * (1 - i.discount_percent / 100.0)), 0) AS monetary FROM customers c LEFT JOIN orders o ON o.customer_id = c.customer_id LEFT JOIN order_items i ON i.order_id = o.order_id GROUP BY c.customer_id, c.customer_name) SELECT customer_name, frequency, ROUND(monetary, 2) AS monetary, CASE WHEN frequency <= 1 THEN 'One-Time' WHEN frequency <= 4 THEN 'Occasional' ELSE 'Loyal' END AS segment FROM customer_value ORDER BY monetary DESC LIMIT 10",
}

for title, query in advanced_queries.items():
    print(f'### {title}')
    display(pd.read_sql_query(query, connection))

### RANK and DENSE_RANK

       customer_name  lifetime_value  value_rank  dense_rank
0     Yatin Dhaliwal       125061.20           1           1
1       Liam Chander       116091.71           2           2
2       Dalbir Hegde       115815.77           3           3
3         Reva Dugar       115179.68           4           4
4  Varenya Sabharwal       100300.41           5           5
5       Maya Chauhan        99861.51           6           6
6     Lakshit Ramesh        90579.34           7           7
7         Reva Soman        89413.31           8           8
8        Daksh Sarin        82627.95           9           9
9         Priya Modi        82533.49          10          10

### Running Total

   sales_date  daily_revenue  running_revenue
0  2020-01-03        7603.30          7603.30
1  2020-01-04       15520.07         23123.37
2  2020-01-05        7799.23         30922.60
3  2020-01-10       25867.93         56790.52
4  2020-01-11       11426.57         68217.10
5  2020-01-13       19603.50         87820.60
6  2020-01-14        3040.72         90861.32
7  2020-01-15        1298.22         92159.54
8  2020-01-17       20840.05        112999.59
9  2020-01-20        7582.27        120581.86

### CTE Monthly Revenue

   sales_month     revenue
0      2020-01   224624.95
1      2020-02   155262.40
2      2020-03   154816.38
3      2020-04   147597.29
4      2020-05   205707.03
..         ...         ...
75     2026-04   166817.19
76     2026-05   112943.64
77     2026-06   184829.18
78     2026-07   102281.75
79     2026-08  1461562.83

[80 rows x 2 columns]

### Cohort Retention

   cohort_month  month_number  active_customers
0    2020-01-01             0                20
1    2020-01-01             1                 2
2    2020-02-01             0                12
3    2020-03-01             0                14
4    2020-03-01             3                 1
5    2020-04-01             0                14
6    2020-05-01             0                13
7    2020-05-01             1                 1
8    2020-05-01             2                 1
9    2020-06-01             0                13
10   2020-07-01             0                12
11   2020-07-01             1                 1

### Customer Segmentation

       customer_name  frequency   monetary segment
0     Yatin Dhaliwal          6  125061.20   Loyal
1       Liam Chander          5  116091.71   Loyal
2       Dalbir Hegde          5  115815.77   Loyal
3         Reva Dugar          6  115179.68   Loyal
4  Varenya Sabharwal          6  100300.41   Loyal
5       Maya Chauhan          5   99861.51   Loyal
6     Lakshit Ramesh          5   90579.34   Loyal
7         Reva Soman          6   89413.31   Loyal
8        Daksh Sarin          6   82627.95   Loyal
9         Priya Modi          5   82533.49   Loyal

## 10. Step 6 – CLI Reporting Tool

The reporting tool accepts report names and optional date filters. Each command prints a formatted preview and exports CSV and TXT files to `output/reports/`.

In [11]:
!{sys.executable} scripts/report_cli.py --report revenue
!{sys.executable} scripts/report_cli.py --report top_customers
!{sys.executable} scripts/report_cli.py --report retention

Traceback (most recent call last):
  File "d:\Samradni Dahiphale\Projects\Celebal task\Data_Engineering_Internship_Celebal_Technologies\Assignment 8\ecommerce-analytics-system\scripts\report_cli.py", line 12, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'
Traceback (most recent call last):
  File "d:\Samradni Dahiphale\Projects\Celebal task\Data_Engineering_Internship_Celebal_Technologies\Assignment 8\ecommerce-analytics-system\scripts\report_cli.py", line 12, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'
Traceback (most recent call last):
  File "d:\Samradni Dahiphale\Projects\Celebal task\Data_Engineering_Internship_Celebal_Technologies\Assignment 8\ecommerce-analytics-system\scripts\report_cli.py", line 12, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'

## 11. Step 7 – Testing

The automated suite checks data validation, database integrity, report generation, and edge-case handling.

In [14]:
!{sys.executable} scripts/test_runner.py
test_summary = pd.read_csv(project_root / 'output' / 'tests' / 'test_summary.csv')
test_summary

==========================================
E-COMMERCE ANALYTICS TEST REPORT
==========================================
Total Tests: 42
Passed: 42
Failed: 0
Warnings: 0
Execution Time: 0.18 sec
Project Status: PASSED
==========================================

..........................................
----------------------------------------------------------------------
Ran 42 tests in 0.179s

OK

   total_tests  passed  failed  warnings  execution_seconds  status
0           42      42       0         0               0.18  PASSED

## 12. Project Features

- [x] Data Generation
- [x] Data Cleaning
- [x] SQLite Database
- [x] SQL Analytics
- [x] Advanced SQL
- [x] CLI Reporting
- [x] Testing
- [x] Reports
- [x] Documentation

## 13. Key Learnings

- Built a complete data pipeline from source files to analytical reports.
- Applied data-quality checks before database loading.
- Designed relational tables with keys, constraints, and indexes.
- Used joins, aggregations, views, CTEs, and window functions for business analysis.
- Performed cohort retention and RFM-style customer segmentation.
- Created reusable command-line reports with date filters.
- Exported reports in CSV and TXT formats.
- Tested normal workflows and failure paths using automated tests.

## 14. Conclusion

This project demonstrates an end-to-end e-commerce analytics workflow using Python and SQLite. Raw data is transformed into validated database records and then converted into business-focused reports. Advanced SQL features provide customer, product, revenue, retention, and segmentation insights. The CLI and automated tests make the project practical, repeatable, and ready for further extension.

In [13]:
connection.close()
print('Notebook execution completed successfully.')

Notebook execution completed successfully.